fhdsl/AI_for_Efficient_Programming

- .github/workflows/pull_request.yml
- 06-understanding_other_ppl_code.Rmd
Having trouble committing branches to main - Candace suggested this might work (seems to be something wonky with how github is dealing with the OTTR_Template files)
> Update git config steps

- .github/workflows/starting-course.yml
Reverts fhdsl/AI_for_software#8
> Revert "Update starting-course.yml"

- .github/workflows/render-all.yml
Hotfix to enable checkout inside repo
> [bug fix] - checkout inside github actions

- 06-understanding_other_ppl_code.Rmd
> Adding a dinosaur cartoon for Howard's quotation

- 01-intro.Rmd
Added CodeWhisperer and CoPilot to the intro section on chatbots and bolded the fact that we do not endorse any particular bot. Also added a dino cartoon and simplified the introduction
> [INTRODUCTION] Adding additional chatbots

- 01-intro.Rmd
Added Phind (just learned about it from Fred) and also alphabetized the order of the AI bots, because the previous order of "how I learned about them" seemed untidy.
> [INTRO] Update and alphabetize bot order

- 06-understanding_other_ppl_code.Rmd
Quick update linking an example in the understanding code chapter to the refactoring code chapter.
> [SUMMARIZATION] Adding link to refactoring chapter

- 01-intro.Rmd
I accidently reviewed a merged pr . this is a test to figure out what to do
> adding random change for test of reopening PR

- 04-annotation.Rmd
- index.Rmd
- resources/dictionary.txt
Cleaning up the front page with lesson duration details, mostly for coursera's purposes..
> Clean up front page with times and description

- index.Rmd
Anything yall would add to these?
> Add some learning objectives

- 01-intro.Rmd
- Appendix.Rmd
- _bookdown.yml
- cloud-computing.Rmd
- resources/dictionary.txt
Added some information on cloud computing to make it easier to link AnVIL to this course. Began a reorganization of the AI chatbots in the introduction to bring attention to the browser-based bots and the IDE-based bots, including AWS' cloud platform tool. This is in preparation for future content in the AI specialization.
> [APPENDIX] adding cloud computing information

- 03-refactoring.Rmd
> [Refactoring] Remove quotations and Add summary

- 01-intro.Rmd
Adding more explicit information on cloud computing
> [Cloud Computing] Adding details on cloud computing to intro

- 01-intro.Rmd
- resources/dictionary.txt
I was a bit quick on the draw and merged the last introduction PR as Candace submitted her suggested changes. They were good changes so I created a new PR to add them.
> [Introduction] Adding Candace's edits on IDEs

- 01-intro.Rmd
In an unexpected plot twist, the information I originally got from Dragonfly on Poe was incorrect. I must have asked the wrong questions. 
This PR adds the correct information about Dragonfly (it is a Microsoft invention, but still not very good for use in software development).
> [Introduction] Correcting information about Dragonfly on Poe

- 01-intro.Rmd
The Dragonfly AI as implemented by Poe gives me different answers to the same question and shouldn't be trusted, so I removed it entirely.
> [Introduction] Removing all information about Dragonfly

- index.Rmd
I was adding the course to the [ITN website](https://www.itcrtraining.org/courses) and made some images about the audience and content that I thought could be helpful within the course.
> adding intro slides about audience and concepts

- 05-annotation.Rmd
This PR adds the learning objectives and quiz necessary to upload this course on Coursera.
> [ANNOTATION] Add learning objectives

- 03-writing_code.Rmd
This PR adds learning objectives to the chapter on Writing Code.
> [Writing Code] Add learning objectives

- GA_Script.Rhtml
- _output.yml
I'm proposing we AI for software underneath its own Google Analytics property (separate from hutchdatascience.org) so we can see specifically where users are going and what pages of the course are attracting the most traffic.
In order to do this, I made a new property underneath [hutchdasl@gmail.com](mailto:hutchdasl@gmail.com) account and I'm putting the new property tag here.
> Add Google Analytics

- 01-intro.Rmd
Because we thought the image of a dinosaur with an angel and a devil on its shoulders would be cute.
> [Intro] Add dinosaur illustration to code of ethics

- GA_Script.Rhtml
> Measurement ID in GA_Script.Rhtml

- quizzes/quiz_ch6.md
> adding one more change to ch 6 quiz

- About.Rmd
Giving Ava credit for what she wrote
> [About] Update authorships

- About.Rmd
Adding authorship of the introduction chapter to about.rmd
> add introduction authorship

- 06-understanding_other_ppl_code.Rmd
When going through the Understanding chapter, I realized there were two sentences back to back that said the same thing. This removes one of them.
> [Understanding] Remove redundant sentence

- index.Rmd
Link was forming in a problematic way.
Also adding leanpub link
> Update index.Rmd - broken link

- 01-intro.Rmd
- 02-ethics.Rmd
- 03-writing_code.Rmd
- 04-refactoring.Rmd
- 05-annotation.Rmd
- 06-understanding_other_ppl_code.Rmd
- 07-bio_code.Rmd
- resources/dictionary.txt
This PR creates embedded videos for each section (introductory and summary videos). The embedded links point to the videos posted on YouTube.
> [General] Add links to YouTube videos
